tests: new actions

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,19 +11,29 @@ jobs:
         os: [ubuntu-latest, macos-latest]
     runs-on: ${{ matrix.os }}
     steps:
-    - uses: actions/checkout@v4
-    - uses: cachix/install-nix-action@v30
-      with:
-        nix_path: nixpkgs=channel:nixos-unstable
-    - run: |
-        if grep -R --exclude stdlib-extended.nix literalExample modules ; then
-          echo "Error: literalExample should be replaced by literalExpression" > /dev/stderr
-          exit 1
-        fi
-    - run: nix-build --show-trace -A docs.jsonModuleMaintainers
-    - run: ./format -c
-    - run: nix-shell --show-trace . -A install
-    - run: yes | home-manager -I home-manager=. uninstall
-    - run: nix-shell --show-trace --arg enableBig false --pure tests -A run.all
-      # Somebody please help us fix the macos tests.
-      if: matrix.os != 'macos-latest'
+      - uses: actions/checkout@v4
+      - uses: nixbuild/nix-quick-install-action@v29
+      - name: Restore and save Nix store
+        uses: nix-community/cache-nix-action@v5
+        with:
+          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
+          # do purge caches
+          purge: true
+          # purge all versions of the cache
+          purge-prefixes: build-${{ runner.os }}-
+          # created more than 0 seconds ago relative to the start of the `Post Restore` phase
+          purge-created: 0
+          # except the version with the `primary-key`, if it exists
+          purge-primary-key: never
+      - run: |
+          if grep -R --exclude stdlib-extended.nix literalExample modules ; then
+            echo "Error: literalExample should be replaced by literalExpression" > /dev/stderr
+            exit 1
+          fi
+      - run: nix-build --show-trace -A docs.jsonModuleMaintainers
+      - run: ./format -c
+      - run: nix-shell --show-trace . -A install
+      - run: yes | home-manager -I home-manager=. uninstall
+      - run: nix-shell --show-trace --arg enableBig false --pure tests -A run.all
+        # Somebody please help us fix the macos tests.
+        if: matrix.os != 'macos-latest'
